### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by xinyang12** [starknet-edu/deploy-cairo1-demo#3]
When I used 
starknet deploy --class_hash <class_hash> --account version_11
there's an error:
Got BadRequest while trying to access https://alpha4.starknet.io/feeder_gateway/simulate_transaction?blockNumber=pending&skipValidate=false. Status code: 500; text: {"code": "StarknetErrorCode.TRANSACTION_FAILED"

Don't know how to fix, thanks

**Comment by xinyang12** [comment]
Look like the constructor params are supposed to be specified but I forgot

**Comment by khadni** [comment]
@xinyang12 Did you wait for your account to be deployed first? (i.e. transaction status should be at least "passed")

**Comment by l-henri** [comment]
Looks like the issue is solved :)
