### ISSUE TITLE
Copy paste of the contract will not work

### ISSUE THREAD

**Issue by glihm** [starknet-edu/deploy-cairo1-demo#4]
Hello,

It could be a valuable info for the reader to remind that the `class hash` is computed from several inputs described in the [documentation](https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/class-hash/#computing_the_cairo_1_class_hash).

As a consequence, if the contract's code from this sample is copied and pasted, the `Starknet` gateway will return a `400 bad request` specifying that the class hash already exists (`CLASS_ALREADY_DECLARED`).

**Comment by l-henri** [comment]
Good call! We added this in the documentation.
