### ISSUE TITLE
Compile your contract to Sierra instead of JSON ?

### ISSUE THREAD

**Issue by 0xKubitus** [starknet-edu/deploy-cairo1-demo#6]
Hey, 
I was following this tutorial along this video: https://www.youtube.com/watch?v=JB53QUFJGvA&t=755s
and noticed that there might be a typo in this repo's README:

![Screenshot from 2023-03-28 21-50-42](https://user-images.githubusercontent.com/102651969/228353003-2a1fc1be-d879-4d4e-bdd9-251404e21f61.png)

As we want to compile with Sierra, I would assume that the correct command is: cargo run --bin starknet-compile -- ../hello_starknet.cairo ../hello_starknet**.sierra** --replace-ids

Could you let me know if there is something I got wrong here, please? (because for me this was the only solution that worked to deploy my first contract)

Anyways, thanks for the tutorial it's now time for me to go bragging on Twitter about my first deployed Cairo 1 contract ! ;)

**Comment by l-henri** [comment]
Hello!
What matters is that you are using the right tool (starknet-compile) to compile your contract. The file extension is not important.
And the output of the compile tool is indeed a json, not sierra code :)

**Comment by l-henri** [comment]
Good bragging to you!
